src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use DateTimeInterface;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 */
class Commande
{


    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")

     */
    private $id;

    /**
     * @ORM\Column(type="float", nullable=true)

     */
    private $prixTotal;


    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="Commandes")

     */
    private $emailuser;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message=" Adresse devrait etre non vide")
     */
    private $adresse;
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message=" Adresse devrait etre non vide")

     */
    private $nom;
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message=" Adresse devrait etre non vide")

     */
    private $prenom;
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message="Description Adresse devrait etre non vide")

     *
     */
    private $descriptionAdresse;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message="Gouvernorat devrait etre non vide")

     */
    private $gouvernorat;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Type(
     *     type="integer",
     *      message="le code postal doit etre écrit par des chiffres uniquement")
     *
     * @Assert\Length(
     *     min=4,
     *     max=4,
     *     minMessage="Le code postal doit etre composé par 4 chiffres",
     *     maxMessage="Le code postal doit etre composé par 4 chiffres"
     * )
     * @Assert\NotBlank(message="Code Postal devraitt etre non vide")

     */
    private $codePostal;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\NotBlank(message="Numero Telephone devrait etre non vide")
     * @Assert\Length(
     *     min=12,
     *     max=12,
     *     minMessage="Le numéro téléphone doit etre composé par 8 chiffres",
     *     maxMessage="Le numéro téléphone doit etre composé par 8 chiffres"
     * )
     * @Assert\Type(
     *     type="integer",
     *      message="le numéro téléphone doit etre écrit par des chiffres uniquement")

     */
    private $numeroTelephone;

    /**
     * @ORM\ManyToOne(targetEntity=Article::class)

     */
    private $Articles;
    /**
        * @ORM\OneToMany(targetEntity=Livraison::class, mappedBy="Commande")
     */
    private $livraisons;




    public function __construct()
    {
        $this->livraisons = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getPrixTotal(): ?float
    {
        return $this->prixTotal;
    }

    public function setPrixTotal(float $Prixtotal): self
    {
        $this->prixTotal = $Prixtotal;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }
    public function getNom(): ?string
    {
        return $this->nom;
    }
    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }
    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }
    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDescriptionAdresse(): ?string
    {
        return $this->descriptionAdresse;
    }

    public function setDescriptionAdresse(?string $descriptionadresse): self
    {
        $this->descriptionAdresse = $descriptionadresse;

        return $this;
    }

    public function getGouvernorat(): ?string
    {
        return $this->gouvernorat;
    }

    public function setGouvernorat(string $gouvernorat): self
    {
        $this->gouvernorat = $gouvernorat;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->codePostal;
    }

    public function setCodePostal(int $codepostal): self
    {
        $this->codePostal = $codepostal;

        return $this;
    }

    public function getNumeroTelephone(): ?int
    {
        return $this->numeroTelephone;
    }

    public function setNumeroTelephone(int $numerotelephone): self
    {
        $this->numeroTelephone = $numerotelephone;

        return $this;
    }

    public function getArticles(): ?Article
    {
        return $this->Articles;
    }

    public function setArticles(?Article $Articles): self
    {
        $this->Articles = $Articles;

        return $this;
    }

    /**
     * @return Collection|Livraison[]
     */
    public function getLivraisons(): Collection
    {
        return $this->livraisons;
    }

    public function addLivraison(Livraison $livraison): self
    {
        if (!$this->livraisons->contains($livraison)) {
            $this->livraisons[] = $livraison;
            $livraison->setCommande($this);
        }

        return $this;
    }

    public function __toString()
    {
        return(string)$this->getId();
    }

    public function getEmailuser(): ?User
    {
        return $this->emailuser;
    }

    public function setEmailuser(?User $emailuser): self
    {
        $this->emailuser = $emailuser;

        return $this;
    }



}

src/Controller/PromotionController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Livraison;
use App\Entity\Materiel;
use App\Entity\MaterielType;
use App\Entity\Promotion;
use App\Entity\User;
use App\Form\PromotionType;
use App\Repository\PromotionRepository;
use Dompdf\Dompdf;
use Dompdf\Options;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\Exception\TransportExceptionInterface;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Annotation\Route;
use GuzzleHttp\Psr7\UploadedFile;
use Symfony\Component\HttpFoundation\JsonRespImageonse;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;


class PromotionController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(): Response
    {   $promotion=$this->getDoctrine()->getRepository(Promotion::class)->findAll();
        $article=$this->getDoctrine()->getRepository(Article::class)->findAll();
        return $this->render('home.html.twig',['article'=>$article,'promotion'=>$promotion]);
    }

    /**
     * @Route("/admin/promotion/{id}", name="promo")
     */
    public function indexP($id): Response
    {
        $promotion=$this->getDoctrine()->getRepository(Promotion::class)->find($id);
        if(!$promotion){
            throw $this->createNotFoundException('Aucun produit ne correspond à l\' id '.$id);
        }
        return $this->render('promotion/show.html.twig', [
            'promotion' =>$promotion
        ]);
    }
    /**
     * @Route("/promotions/{id}", name="showpromo")
     */
    public function showprom($id): Response
    {
        $promotion=$this->getDoctrine()->getRepository(Promotion::class)->find($id);
        if(!$promotion){
            throw $this->createNotFoundException('Aucun produit ne correspond à l\' id '.$id);
        }
        return $this->render('promotion/showprom.html.twig', [
            'promotion' =>$promotion
        ]);
    }

    /**
     * @Route ("/admin/recherchepromotion",name="recherchepromo")
     */
    public function recherche(PromotionRepository $repository , Request $request , PaginatorInterface $paginator )
    {
        $data=$request->get('search');
        $promotion=$repository->SearchName($data);

        $promotion = $paginator->paginate(
            $promotion, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            3) ;/*limit per page*/

        return $this->render('admin/promotion/admin.html.twig', array(
            'promotion' => $promotion));

    }

    /**
     * @Route("/admin/listtriepromo", name="listtriepromo")
     */
    public function listTriepromo(PaginatorInterface $paginator , Request $request)
    {
        $ar = $this->getDoctrine()->getRepository(Promotion::class)->listOrderByRemise();
        $promotion = $paginator->paginate(
            $ar, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            3) ;/*limit per page*/

        return $this->render('admin/promotion/admin.html.twig', [
            'promotion' => $promotion]);



    }

    /**
     * @Route("/admin/promotion", name="promotion")
     */
    public function readPromotion(PaginatorInterface $paginator , Request $request): Response
    { $repo=$this->getDoctrine()->getRepository(Promotion::class);
        $listePromo=$repo->DateExpr();

        $listePromo = $paginator->paginate(
            $listePromo, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            3) ;/*limit per page*/

        return $this->render('admin/promotion/admin.html.twig', array(
            'promotion' => $listePromo));


    }
    /**
     * @Route("/promotions", name="h_promotion")
     */
    public function readPromotions(): Response
    { $repo=$this->getDoctrine()->getRepository(Promotion::class);
        $listePromo=$repo->DateExpr();

        return $this->render('promotion/index.html.twig',[
            'promotion'=>$listePromo]);

    }




    /**
     * @param Request $request
     * @param MailerInterface $mailer
     * @return Response
     * @throws TransportExceptionInterface
     * @Route("/admin/promotion/test/ajouter", name="new")
     */
    public function createPromotion(Request $request,MailerInterface $mailer)
    {   $em=$this->getDoctrine()->getManager();
        $user=$em->getRepository(User::class)->findAll();
        $promotion=new Promotion();
        $form=$this->createForm(PromotionType::class , $promotion);
        $form->add('Ajouter',SubmitType::class);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            /**
             * @var UploadedFile $file
             */
            $file = $form->get('img')->getData();
            $fileName = bin2hex(random_bytes(6)).'.'.$file->guessExtension();
            $file->move ($this->getParameter('images_directory'),$fileName);
            $promotion->setImg("http://127.0.0.1:8000/upload/" . $fileName);

            $em->persist($promotion);
            $em->flush();
            foreach ($user as $u)
            {
                $email = (new Email())
                    ->from('para.diseesprit@gmail.com')
                    ->to($u->getEmail())
                    ->priority(Email::PRIORITY_HIGH)
                    ->subject('[Paradise] Nouvelle Promotion !')
                    //->text('Sending emails is fun again!')
                    ->html('<p>Bonjour cher(e) Mr/Mme </p><br>
                   <p>Une nouvelle promotion est bien lancée.  votre commande sera livré le '.($promotion->getNompromotion()).' avec le livreur' .$promotion->getDescription().'</p><br>');
                $mailer->send($email);}
            return $this->redirectToRoute('promotion');

        }

        return $this->render('admin/promotion/ajouter.html.twig',[
            'form'=>$form->createView()]);

    }
    /**
     * @param Request
     * @return Response
     * @Route("/admin/promotion/update/{id}" , name="u")
     */
    public function updatePromotion(Request $request,$id){
        $repo=$this->getDoctrine()->getRepository(Promotion::class);
        $promo=$repo->find($id);
        $form=$this->createForm(PromotionType::class,$promo);
        $form->add('Modifier',SubmitType::class);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            /**
             * @var UploadedFile $file
             */
            $file = $form->get('img')->getData();
            $fileName = bin2hex(random_bytes(6)).'.'.$file->guessExtension();
            $file->move ($this->getParameter('images_directory'),$fileName);
            $promo->setImg("http://127.0.0.1:8000/upload/" .$fileName);
            $em=$this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute('promotion');
        }
        else{
            return $this->render('admin/promotion/modifier.html.twig',[
                'form'=>$form->createView()]);
        }
    }
    /**
     * @Route("/admin/promotion/delete/{id}",name="d")
     */
    public function deletePromotion(int $id): Response
    {
        $em=$this->getDoctrine()->getManager();
        $repo=$this->getDoctrine()->getRepository(Promotion::class);
        $promo=$repo->find($id);
        $em->remove($promo);
        $em->flush();

        return $this->redirectToRoute('promotion');

    }
    /**
     * @param Request $request
     * @param MailerInterface $mailer
     * @return Response
     * @throws TransportExceptionInterface
     * @Route("/admin/promotion/test/rappel/{id}", name="rappel")
     */
    public function rappelPromotion(MailerInterface $mailer,$id)
    {
        $em = $this->getDoctrine()->getManager();
        $repo = $this->getDoctrine()->getRepository(Promotion::class);
        $user = $em->getRepository(User::class)->findAll();
        $promo = $repo->find($id);


        foreach ($user as $u) {
            $email = (new Email())
                ->from('para.diseesprit@gmail.com')
                ->to($u->getEmail())
                ->priority(Email::PRIORITY_HIGH)
                ->subject('[Paradise] Rappel Promotion ' . ($promo->getNompromotion()) . '!')
                //->text('Sending emails is fun again!')
                ->html('<p>Bonjour cher(e) Mr/Mme </p><br>
                   <p>Cette promotion est toujours validé. Venez avant que la promotion se termine.</p> <br>
                   Venez avant que la promotion <span style="color: rgb(226, 80, 65);"><strong>se termine</strong></span> <strong>!!!</strong><br><br> MERCI. ');
            $mailer->send($email);
        }
        return $this->redirectToRoute('promotion');


    }
    /**
     * @Route("/imprimerPromotion", name="promotion_liste")
     */
    public function imprimerpromo()
    {
        // Configure Dompdf according to your needs
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');

        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);
        $promo = $this->getDoctrine()->getRepository(Promotion::class)->findAll();


        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('Promotion/test.html.twig', ["promotion" => $promo]);

        // Load HTML to Dompdf
        $dompdf->loadHtml($html);

        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (inline view)
        $dompdf->stream("mypdf.pdf", [
            "Attachment" => false
        ]);

    }

templates/promotion/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<style>
    .azerty{
        width: 600;
        height: 370;
    }
</style>

    <section class="midium-banner">
        <div class="container">
            <div class="row">
                {% for c in promotion %}
                <div class="col-lg-6 col-md-6 col-12">
                    <div class="single-banner">

                        <div class="azerty">
                        <img  src="{{ asset(''~c.img~'') }}">
                        </div>
                        <div class="content">
                            <h3>{{ c.nompromotion }}</h3>
                            <a href="{{ path('showpromo', {'id': c.id}) }}">Voir la promotion</a>
                        </div>
                    </div>
                </div>

                {% endfor %}
            </div>
        </div>
    </section>
    <br>
{% endblock %}

templates/promotion/promo.html.twig
{% include 'app/nav.html.twig' %}

<!-- Slider Area -->
<section class="hero-slider">
    <!-- Single Slider -->
    <div class="single-slider">
        <div class="container">
            <div class="row no-gutters">
                <div class="col-lg-9 offset-lg-3 col-12">
                    <div class="text-inner">
                        <div class="row">
                            <div class="col-lg-7 col-12">
                                <div class="hero-text">
                                    {% for c in promotion %}
                                        <h1><span>PLUS QUE 50% REMISE </span>{{ c.nompromotion }}</h1>
                                        <h4>{{ c.description }} </h4>
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="section-title">
                                                    <h2>Les Articles de la Promotion</h2>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ End Single Slider -->
</section>
<!--/ End Slider Area -->


{% include 'app/footer.html.twig' %}

templates/promotion/promotion.html.twig
    {{ data|json_encode }}

templates/promotion/show.html.twig
{% include 'admin/admin.html.twig' %}
{% include 'admin/navbar.html.twig' %}
{% include 'admin/sidebar.html.twig' %}
{% block body %}
<div class="wrapper" style="padding-top: 60px">

    <div class="content-wrapper">
        <section class="content">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        <strong>Nom de la promotion : </strong>
                        {{ promotion.nompromotion }}</h3>
                </div>
                <div class="card-body">
                    <div> <p>
                            <strong> Remise de la promotion : </strong>
                            {{ promotion.remise }}
                        </p>
                    </div><br>
                    <div> <p>
                            <strong> Description de la promotion : </strong>
                            {{ promotion.description }}
                        </p>
                    </div><br>
                    <div> <p>
                            <strong> Image de la promotion : </strong>
                            <img src="{{ asset(''~promotion.img~'') }}"  >
                        </p>
                    </div><br>
                    <div> <p>
                            <strong> Articles de la promotion : </strong><br>



                            {% for promotion in promotion.articles %}
                                {{ promotion.id }} <br>
                            {% endfor %}


                        </p>
                    </div><br>
{#
            <div> <p>
        <strong> Articles de la promotion : </strong>
            {{ promotion.articles }}
                        </p> #}
                    </div><br>
                </div>

        </section>




    </div>
</div>
{% endblock %}

templates/promotion/showprom.html.twig
{% extends 'base.html.twig' %}


{% block body %}
<br>
            <center>
                <img src="{{ asset(''~promotion.img~'') }}">
            </center>
<br>
    <section class="shop-newsletter section">
    <div class="container">
    <div class="inner-top">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 col-12">
                <!-- Start Newsletter Inner -->
                <div class="inner">
                    <h4>{{ promotion.nompromotion }}</h4>
                    <p>{{ promotion.description }}</p>
                </div>
                <!-- End Newsletter Inner -->
            </div>
        </div>
    </div>
</div>
    </section>

    <div class="row">
        <div class="col-12">
            <div class="section-title">
                <h2>Les produits de la promtion</h2>
            </div>
        </div>
    </div>

<style>.aa{
        text-decoration:line-through;
    }</style>

    <div class="row">
        <center>
        <div class="col-md-9">

          <div class="grid">

          {% for p in promotion.articles %}

            <div class="row">
                <div class="col-sm-12">
                    <div class="product-grid">
                        <div class="product-image">
                            <a href="#" class="image">
                                <img class="pic-1" src="{{ asset(''~p.img~'') }}">
                            </a>

                        </div>
                        <div class="product-content">
                            <h3 class="title"><a>{{ p.nom }}</a></h3>
                            <div class="aa"> {{ p.prix }} DT</div>
                            <div class="price"> {{ p.prix - (p.prix * promotion.remise) }} DT</div>
                        </div>
                    </div>
                </div>
            </div>

        {% endfor %}

            </div>

        </div>
        </center>
    </div>

<br>
{% endblock %}

templates/promotion/test.html.twig
<h1 >Liste des promotions</h1>
<table id="customers">
    <thead>
    <tr>
        <th>ID Promotion</th>
        <th>Nom du promotion</th>
        <th>Remise</th>
        <th>Description</th>

    </tr>
    {% for promo in promotion %}
        <tr>
            <td>{{ promo.id }}</td>
            <td>{{ promo.nompromotion }}</td>
            <td>{{ promo.remise }}</td>
            <td>{{ promo.description }}</td>

        </tr>
    {% endfor %}

</table>



<style>
    ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #333;
    }

    li {
        float: left;
    }

    li a {
        display: block;
        color: white;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
    }

    li a:hover:not(.active) {
        background-color: #111;
    }

    .active {
        background-color: #4CAF50;
    }
    #customers {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    #customers td, #customers th {
        border: 1px solid #ddd;
        padding: 8px;
    }

    #customers tr:nth-child(even){background-color: #f2f2f2;}

    #customers tr:hover {background-color: #ddd;}

    #customers th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #4CAF50;
        color: white;
    }

</style>